#!/bin/bash

echo "Enter your passward: "
read password
length="${#password}"

if [[ $length -ge 8 ]]
then
        echo "$password" | grep -q [0-9]
        if [[ $? -eq 0 ]]
        then

                echo "$password" | grep -q [A-Z]
                if [[ $? -eq 0 ]]
                then

                        echo "$password" | grep -q [a-z]
                        if [[ $? -eq 0 ]]
                        then
                                echo "strong password"
                        else
                                echo "WEAK PASSWORD-should contain a lower case letter"
                        fi
                else
                        echo "WEAK PASSWORD-should contain a upper case letter"
                fi
        else
                echo "WEAK PASSWORD-should contain a number"
        fi
else
        echo "Length is too small-minimum 8 length"
fi
